### ISSUE TITLE
Проблема с надписями в битвах 

### ISSUE THREAD

**Issue by Eremenk** [ThatOneMeganium/Mother3RUS#3]
![Mother 3 rus  patched _1634457405706](https://user-images.githubusercontent.com/92682627/137634074-efa96245-1c20-46c5-877c-b81d1db1070b.png)
При каждой битве с любым врагом порой появляется непонятная белеберда из цифр и букв

**Comment by ThatOneMeganium** [comment]
Вроде исправил.
Просто во время переноса перевода с 1.2 на 1.3 некоторые строки были криво скопированы

**Comment by MAGNAT2645** [comment]
Кстати, рекомендую не делать релиз на каждое изменение (слишком частые релизы не всегда хорошо, скорее раздражает). Если изменение не критичное и мелкое, то просто делай несколько коммитов до тех пор, пока не посчитаешь нужным выпустить новую версию (там же описываешь все новые изменения с последней версии).
