### ISSUE TITLE
Опечатка + имена врагов и предметов

### ISSUE THREAD

**Issue by MAGNAT2645** [ThatOneMeganium/Mother3RUS#7]
[Степан Лимонов](https://vk.com/ded_prikolist):
> З потеряли
![изображение](https://user-images.githubusercontent.com/11666918/144760356-7f478cb3-9da0-4162-bfb5-22d7967b0b26.png)

Также, я рекомендую заменить лишние заглавные буквы на строчные в именах предметов и врагов.
Например, `Древний Банан` -> `Древний банан`

**Comment by ThatOneMeganium** [comment]
Названия предметов и в оригинале имели лишние заглавные буквы, но я подумаю на счёт этого.

**Comment by MAGNAT2645** [comment]
> Названия предметов и в оригинале имели лишние заглавные буквы, но я подумаю на счёт этого.

Так и в других играх так же, это у них правило вроде такое в английском, наши при переводе на русский (в идеале) не повторяют заглавие букв.
